# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
#- task: DotNetCoreCLI@2
#  displayName: 'Test project'
#  inputs:
#    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Publish..'
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c Release -o publish'
    zipAfterPublish: false
    modifyOutputPath: false